### ISSUE TITLE
500 Internal server error when ticking game

### ISSUE THREAD

**Issue by AlexanderPineiro** [sekassel/stp-24-server-issues#30]
**Describe the bug**
After posting a new empire the game won't properly tick anymore, periods still seem to increase but nothing else works properly

**To Reproduce**
Patch a new empire with the following dto: 
```java
new CreateEmpireDto("The Scourge", "CONSUME", "#000000",
3, 3, bestSpawnSystem._id(), List.of("__dev__"), Map.of(), List.of(), List.of(), Map.of(),
Map.of())
```
bestSpawnSystem.id() is the id of a specific system that exists in the game.
Posting the empire works and doesn't throw an error, however the population in the system seems to be null and something else seems to also crash.

**Expected behavior**
The game still ticks after posting a new empire

**Additional context**
Errormessage:
{"statusCode":500,"message":"Internal server error"}
The empire seems to get created and there are buildings in it's homesystem however since the population seems to be null it causes several issues which might crash other teams that aren't prepared for this.

**Comment by Clashsoft** [comment]
I assume one of your `Map.of()` is the resources. Because you send an empty map, the system cannot initialize its population. You need to initialize the resources yourself with reasonable defaults (that means actually it's not necessary to use the `__dev__` trait).

Though I agree this should not crash the server... it will be fixed in the next patch.

**Comment by APineiro-Uni** [comment]
Properly setting the resources in the creation fixed the issue. Should I keep this open until the crash gets fixed or close it now?

**Comment by Clashsoft** [comment]
It's fixed.
