### ISSUE TITLE
Players can spawn in a trapped location

### ISSUE THREAD

**Issue by AlexanderPineiro** [sekassel/stp-24-server-issues#31]
**Is your feature request related to a problem? Please describe.**
It is possible for a players homesystem to only have a single connection to a system that contains neutral fleets, this essentially causes the player to lose immediately because they have no chance of expanding.

**Describe the solution you'd like**
Make sure that players have at least several systems they can expand into when they are boxed in as described.

**Describe alternatives you've considered**
Try to make it possible for players to somehow dodge these neutral fleets with their explorers and colonizers so they still have an option to expand.

**Additional context**
I don't know whether to qualify this as a feature or a bug but it kind of fits both.

**Comment by Clashsoft** [comment]
I can add checks to ensure the fleets don't spawn in systems neighboring the homesystems. But the overall intent is to provide players with a sense of pride and accomplishment for defeating the rogue fleets.

**Comment by APineiro-Uni** [comment]
That makes sense in general, the main problem is that this is akin to spawning next to a fallen empire in Stellaris that blocks all ways out. It is somewhat worse here because playing tall is less of an option in this game compared to Stellaris.
It would probably be nice to bias neutral fleets towards chockepoints so they gate of something, making defeating them more important. Currently they sometimes only protect one system and can be ignored easily until there is nowhere else to expand to.

**Comment by Clashsoft** [comment]
In the new patch, the chance to spawn large ships was reduced significantly. That should allow all empires to defeat the rogue fleets at some point.

Though the choke points are a nice idea, we cannot change the spawn behavior of rogue fleets in this way in the remaining time.
